name: nexus
version: 1.0.0
description: Sonatype Nexus Repository Manager 3
keywords:
  - Maven Repository
  - NPM Repository
  - Nuget Repository
  - Docker Repository
home: http://www.sonatype.org/nexus/category/nexus-3/
sources:
  - https://github.com/sonatype/docker-nexus3
maintainers:
  - name: Markus M. May
    email: triplem@javafreedom.org
engine: gotpl
