pipeline:
  lint:
    image: soxhub/helm:v2.4.2-b
    commands:
      - helm lint ./drone
      - helm lint ./artifactory-oss
      - helm lint ./artifactory-pro
      - helm lint ./jenkins-dood
      # - helm lint ./nexus
