apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nexus-ss
  labels:
    app: "nexus-ss"
    chart: "nexus-0.0.1"
spec:
  serviceName: "nexus-ss"
  replicas: 1
  template:
    metadata:
      labels:
        app: "nexus-ss"
        chart: "nexus-0.0.1"
    spec:
      initContainers:
      - name: init-fs-prep
        image: busybox
        command: ['sh', '-c', 'chmod 777 /nexus-data']
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data

      containers:
      - name: nexus
        image: "sonatype/nexus3:3.3.2"
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: "-Xms1200m -Xmx1200m"
        - name: NEXUS_CONTEXT
          value: /
        ports:
        - name: http
          containerPort: 8081
#        livenessProbe:
#          httpGet:
#            path: /
#            port: http
#          initialDelaySeconds: 120
#          timeoutSeconds: 5
#        readinessProbe:
#          httpGet:
#            path: /
#            port: http
#          initialDelaySeconds: 5
#          timeoutSeconds: 1
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
  volumeClaimTemplates:
  - metadata:
      name: nexus-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

