apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: "{{ .Chart.Name }}"
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  serviceName: {{ template "fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "sonatype/nexus3:{{ .Values.statefulset.imageTag }}"
        imagePullPolicy: {{ default "" .Values.statefulset.pullPolicy | quote }}
        env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: "{{ .Values.statefulset.javaOpts }}"
        - name: NEXUS_CONTEXT
          value: {{ .Values.statefulset.context }}
        ports:
        - name: http
          containerPort: {{ .Values.statefulset.containerPort }}
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      volumes:
      - name: nexus-data
        hostPath:
          path: {{ .Values.statefulset.persistence.path }}
  volumeClaimTemplates:
  - metadata:
      name: nexus-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.statefulset.persistence.storage }}
