image:
  org: drone
  name: drone
  tag: 0.8.0-rc.3
  agentName: agent
  agentTag: 0.8.0-rc.3
  pullPolicy: Always

# it is a bad idea to change the internalPorts
service:
  http:
    externalPort: 80
    internalPort: 8000
  grpc:
    internalPort: 9000
  docker:
    internalPort: 2375
  type: ClusterIP

ingress:
  enabled: true
  hostname: drone.devpoc1.jamconsultg.com
  labels:
     env: prod

server:
  # Drone server configuration. Values in here get injected as environment variables.
  # See http://readme.drone.io/admin/installation-reference#server-options for a list of possible values.
  env:
    DRONE_DEBUG: false
    DRONE_DATABASE_DRIVER: "postgres"
    # datasource is a kubernetes secret for postgres connection
    # DRONE_DATABASE_DATASOURCE: "drone.sqlite"

    DRONE_OPEN: true
    DRONE_GITHUB: true
    DRONE_GITHUB_PRIVATE_MODE: true
  secret: drone
  resources:
    requests:
      memory: 32Mi
      cpu: 40m
    limits:
      memory: 1Gi
      cpu: 500m

agent:
  # Drone agent configuration. Values in here get injected as
  # environment variables. For a list of possible values, see
  # http://readme.drone.io/admin/installation-reference#server-options
  env:
    DRONE_DEBUG: false
  resources:
    requests:
      memory: 32Mi
      cpu: 40m
    limits:
      memory: 1Gi
      cpu: 500m

# Uncomment this if you want to set a specific shared secret between
# the agents and servers, otherwise this will be auto-generated.
# shared_secret: supersecret
