apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  labels:
    app: "nexus"
    chart: "nexus-0.0.1"
    provider: "devopskube"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "nexus"
        chart: "nexus-0.0.1"
        provider: "devopskube"
    spec:
      containers:
      - name: nexus
        image: "sonatype/nexus3:3.3.2"
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: "-Xms1200m -Xmx1200m"
        - name: NEXUS_CONTEXT
          value: /
        ports:
        - name: http
          containerPort: 8081
#        livenessProbe:
#          httpGet:
#            path: /
#            port: http
#          initialDelaySeconds: 120
#          timeoutSeconds: 5
#        readinessProbe:
#          httpGet:
#            path: /
#            port: http
#          initialDelaySeconds: 5
#          timeoutSeconds: 1
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      volumes:
      - name: nexus-data
        hostPath:
          path: /data/nexus
