apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-agent
  labels:
    app: {{ template "fullname" . }}-agent
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-agent
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: {{ template "fullname" . }}-agent
        image: "{{ .Values.image.org }}/{{ .Values.image.agentName }}:{{ .Values.image.agentTag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DRONE_SERVER
          value: {{ template "fullname" . }}:{{ .Values.service.grpc.internalPort }}
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: secret
        - name: DOCKER_HOST
          value: tcp://{{ template "fullname" . }}-dind:{{ .Values.service.docker.internalPort }}
        {{ range $key, $value := .Values.agent.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{ end }}
        resources:
{{ toYaml .Values.agent.resources | indent 10 }}
